/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.springframework.boot") version "3.2.0"
    id("io.spring.dependency-management") version "1.1.4"
}


repositories {
    mavenCentral()
    flatDir {
        dirs("libs")
    }
}

dependencies {
    implementation(files("libs/aws-sdk-java-bundle-2.30.5-SNAPSHOT.jar"))
    implementation("org.slf4j:slf4j-api:2.0.9")
    implementation("ch.qos.logback:logback-classic:1.4.11")
    implementation("org.json:json:20230227")
    implementation("io.reactivex.rxjava3:rxjava:3.1.8")
    implementation("io.projectreactor:reactor-core:3.6.2")

    implementation("org.eclipse.jetty:jetty-server:11.0.18")
    implementation("org.eclipse.jetty:jetty-servlet:11.0.18")
    implementation("org.eclipse.jetty:jetty-webapp:11.0.18")
    implementation("org.eclipse.jetty.websocket:websocket-jetty-server:11.0.18")
    implementation("org.eclipse.jetty.websocket:websocket-jetty-client:11.0.18")
    implementation("org.eclipse.jetty:jetty-util:11.0.18")
    implementation("org.eclipse.jetty:jetty-http:11.0.18")
    implementation("org.eclipse.jetty:jetty-io:11.0.18")
    implementation("jakarta.servlet:jakarta.servlet-api:5.0.0")
    implementation("org.eclipse.jetty:jetty-security:11.0.18")
    implementation("org.eclipse.jetty:jetty-annotations:11.0.18")
    implementation("org.eclipse.jetty:jetty-plus:11.0.18")
    implementation("org.eclipse.jetty:jetty-xml:11.0.18")
    implementation("org.eclipse.jetty.websocket:websocket-servlet:11.0.18")
    implementation("org.eclipse.jetty.websocket:websocket-core-server:11.0.18")
    implementation("org.eclipse.jetty.websocket:websocket-core-client:11.0.18")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.2")
    implementation("org.springframework.boot:spring-boot-starter-websocket")
    implementation("org.springframework.boot:spring-boot-starter-web")
    compileOnly("org.projectlombok:lombok:1.18.30") // Use the latest version
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    testImplementation(libs.junit.jupiter)
    testImplementation("org.mockito:mockito-core:5.8.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.8.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "org.example.BedrockInitiateClient"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

tasks.withType<JavaCompile> {
    options.annotationProcessorPath = configurations.annotationProcessor.get()
}

